[package]
name = "obj_to_mesh"
version = "0.1.0"
authors = ["Tommaso Checchi <tommaso.checchi1@gmail.com>"]

[dependencies.wavefront_obj]
git = "https://github.com/PistonDevelopers/wavefront_obj.git"

[dependencies]
byteorder = "0.4.2"
clap = "2.0.2"